on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Compiler
        run: |
          sudo apt-get install -y polyml libpolyml-dev
          poly -v

      - name: Build
        run: ./build.sh

      - name: Run tests
        run: ./test.sh
